// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace TPSGameplayTags
{
	/// Ability
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_WeaponFire);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_WeaponSPFire);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cooldown);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_ActivateFail_Cost);
	
	/// Action Tags
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Attack);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Jump);

	/// Weapon
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_WeaponFireBlocked);
	
	/// Input Tags
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interaction);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_SPFire);
	
	/// InitState
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	/// GameplayEvent
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);

	/// Status
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Dying);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death_Death);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Healing);

	/// Movement
	SAMPLEPROJECT_API extern const TMap<uint8, FGameplayTag> MovementModeTags;

	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	/// Event
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_WeaponFire);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_WeaponSPFire);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Fire);
	
	/// Gameplay
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Damage);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_DamageImmunity);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_DamageSelfDestruct);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_FellOutOfWorld);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Damage_Message);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Interaction);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Heal);

	/// Cooldown
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_WeaponSPFire);
}

namespace TPSGGameplayEffectTags
{
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageType_Normal);
}
namespace TPSGameplayCueTags
{
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Character_DamageTaken);
}

namespace TPSUILayerTags
{
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_Menu);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_ACTION_ESCAPE);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_Game);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_GameMenu);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_UI_LAYER_Modal);
}
class FTPSGameplayTagHelper
{
public:
	static FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialsString = false);
};
