// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace TPSGameplayTags
{
	SAMPLEPROJECT_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

	/// Ability
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Type_Action_WeaponFire);
	
	/// Action Tags
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Attack);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Action_Jump);
	
	/// Input Tags
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Mouse);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look_Stick);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	
	/// InitState
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_Spawned);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InitState_GameplayReady);

	/// GameplayEvent
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEvent_Death);

	/// Status
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Crouching);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Status_Death);

	/// Movement
	SAMPLEPROJECT_API extern const TMap<uint8, FGameplayTag> MovementModeTags;

	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Walking);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Falling);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Movement_Mode_Flying);

	/// Event
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Movement_WeaponFire);

	/// Gameplay
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Damage);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_DamageImmunity);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_DamageSelfDestruct);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_FellOutOfWorld);
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Gameplay_Damage_Message);
}

namespace TPSGGameplayEffectTags
{
	SAMPLEPROJECT_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
	
	SAMPLEPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayEffect_DamageType_Normal);
}
